### ISSUE TITLE
Usage videos

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/get-mac#17]
Add a few videos or animations to the README demonstrating usage of `get-mac` command and the Python module `getmac`. These can be recorded using [asciinema](https://asciinema.org/) or other such tools.

**Comment by fortunate-man** [comment]
@GhostofGoes I'd like to do this one!

**Comment by GhostofGoes** [comment]
It's perfectly safe to share your MAC address. You'll notice there are quite a few shared in the `samples/` directory 😄

**Comment by fortunate-man** [comment]
Ok then!

**Comment by GhostofGoes** [comment]
I'm turning in for the night, feel free to comment with more questions and I'll try to get to them in the morning.

**Comment by Komish** [comment]
I see adjustments were requested from @GhostofGoes in PR #18 - let me know if you need additional assistance with this.
