### ISSUE TITLE
Test functionality in a Docker container

### ISSUE THREAD

**Issue by GhostofGoes** [GhostofGoes/get-mac#22]

**Comment by Komish** [comment]
Hi There, I can run a test of this in a Docker container. Was there a specific set of tasks you'd like executed? Perhaps what's being requested in #20 as a guideline? 

How would you like the information contributed back? Perhaps a markdown file? Where in the repository would it fit best?

**Comment by GhostofGoes** [comment]
@Komish Added a comment clarifying in #20

**Comment by Komish** [comment]
@GhostofGoes Understood I'll review and report back!
