### ISSUE TITLE
get-mac returns None in Python 3.6

### ISSUE THREAD

**Issue by minjin1223** [GhostofGoes/get-mac#7]
Hi,
I'm trying to integrate this get_mac_address function on my Python script, but found it returns None from Python 3.6 while it returns correct MAC address on Python 2.7 even though same script is used.

I've gone through getmac.py and found that inetaddr has different value between Python 2.7 and 3.6. 
`def _windows_get_remote_mac_ctypes(host):`
`try:`
`inetaddr = ctypes.windll.wsock32.inetaddr(host))`

I tried inserting the inetaddr value received from Python 2.7 on Python 3.6's getmac.py, and found that it returns MAC address.
Seems like there's difference on ctypes library between Python 2.7 and 3.6. 
Do you have any solution to fix this issue?

Thanks,
Minjin

**Comment by GhostofGoes** [comment]
I was able to reproduce the issue you're having with Python 2.7.14 and 3.6.4 on Windows 10.

Definitely odd, I'll look into it when I get a chance this week.

**Comment by GhostofGoes** [comment]
SendARP expects bytes. Python 2 does str-bytes conversions implicitly, while on Python 3 they have to be done explicitly using .encode(). I added a simple fix, will push to PyPI momentarily.

**Comment by GhostofGoes** [comment]
Fix is pushed to PyPI as version 0.2.3. Let me know if it works.
